name: Terraform GCP Deployment

on:
  push:
    branches: [ feat/terraform-setup-init ]
    # paths:
    #   - 'infra/envs/dev/**'
  pull_request:
    branches: [ feat/terraform-setup-init ]
    # paths:
    #   - 'infra/envs/dev/**'

env:
  TF_WORKSPACE: dev
  WORKING_DIRECTORY: infra/envs/dev

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Terraform Format
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform fmt -check
      
    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: terraform init
      
    - name: Terraform Plan
      working-directory: ${{ env.WORKING_DIRECTORY }}
      # if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      continue-on-error: true
      
    - name: Terraform Apply
      working-directory: ${{ env.WORKING_DIRECTORY }}
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve